language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
sudo: false
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.2.0" --no-interaction  --no-progress
  - travis_retry composer config --global github-oauth.github.com "$GITHUB_TOKEN"
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer update --prefer-dist --no-interaction  --no-progress
script:
  - cp phpunit.sample.xml phpunit.xml
  - vendor/bin/phpunit --debug
