language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
  - hhvm
  - nightly
sudo: false
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
install:
  - phpenv config-rm xdebug.ini || echo "xdebug is not installed"
  - travis_retry composer self-update && composer --version
  - travis_retry composer global require "fxp/composer-asset-plugin:^1.2.0" --no-interaction  --no-progress
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer update --prefer-dist --no-interaction  --no-progress
script:
  - vendor/bin/phpunit --debug
